
name: xlog

#on: [workflow_dispatch]
on:
  push:
#    branches: [ "master", "develop" ]
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  test_xlog:
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    strategy:
      matrix:
        go: [ '1.21' , '1.22' , '1.23', '1.24', '1.25' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test -v ./...
